version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=develop
    networks:
      - app-network

  test:
    build: .
    entrypoint: ["sh", "-c", "mvn test"]
    environment:
      - SPRING_PROFILES_ACTIVE=test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge